# Default values for gotourl.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nsokil/gotourl
  tag: 367d717
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

env:
  port: ":80"
  keylength: "6"
  expirationMillis: "7200000"
  storage: "redis"
  redisUrl: "redis:6379"
  traceDbEnabled: "true"
  jaeger:
    serviceName: "goto-url"
    sampler: "const"
    samplerParam: "1"
    endpoint: "http://jaeger-collector:14268/api/traces"
    reporterLogSpans: "false"

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

redis:
  redisPort: 6379
  usePassword: true
  password: "12345678" # TODO export from secret (use Helm Secrets?)
  master:
    persistence:
      enabled: true
  cluster:
    enabled: false


