apiVersion: v1
kind: Service
metadata:
  name: gotourl-service
  labels:
    app: gotourl
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: gotourl

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gotourl-config-map
  namespace: default
data:
  ENV_PORT: ":80"
  ENV_KEY_LEN: "6"
  ENV_EXPIRATION_MILLIS: "7200000"
  ENV_STORAGE: "redis"
  ENV_REDIS_URL: "redis:6379"
  ENV_TRACE_DB_ENABLED: "true"
  JAEGER_SERVICE_NAME: "goto-url"
  JAEGER_SAMPLER_TYPE: "const"
  JAEGER_SAMPLER_PARAM: "1"
  JAEGER_ENDPOINT: "http://jaeger-collector:14268/api/traces"
  JAEGER_REPORTER_LOG_SPANS: "true"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotourl
  labels:
    app: gotourl
spec:
  selector:
    matchLabels:
      app: gotourl
  replicas: 1
  template:
    metadata:
      name: gotourl
      labels:
        app: gotourl
    spec:
      containers:
      - name: gotourl
        image: nsokil/gotourl:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: gotourl-config-map
        env:
        - name: ENV_REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: REDIS_PASS
