apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    type: local
spec:
  storageClassName: "manual"
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/redis-pv"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
spec:
  storageClassName: "manual"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 700Mi

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.1
        imagePullPolicy: Always
        env:
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: REDIS_PASS
        args: ["--requirepass $(REDIS_PASS)", "--appendonly", "yes", "--save", "900", "1", "--save", "30", "2"]
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - mountPath: "/data"
          name: redis-pv
      volumes:
      - name: redis-pv
        persistentVolumeClaim:
          claimName: redis-pv-claim