apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gotourl-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/app-root: "/index.html"
spec:
  rules:
    - http:
        paths:
          - path: "/index.html"
            backend:
              serviceName: {{ .Release.Name }}-frontend-svc
              servicePort: 80 # todo un-hardcode
          - path: "/js"
            backend:
              serviceName: {{ .Release.Name }}-frontend-svc
              servicePort: 80
          - path: "/"
            backend:
              serviceName: {{ .Release.Name }}-gotourl-svc
              servicePort: 80