apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nsokil/gotourl-frontend:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      restartPolicy: Always
  selector:
    matchLabels:
      app: frontend
