apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-gotourl-configmap
data:
    ENV_PORT: "{{ .Values.env.port }}"
    ENV_KEY_LEN: "{{ .Values.env.keylength }}"
    ENV_EXPIRATION_MILLIS: "{{ .Values.env.expirationMillis }}"
    ENV_STORAGE: "{{ .Values.env.storage }}"
    ENV_REDIS_URL: "{{ .Release.Name }}-redis-master:{{.Values.redis.redisPort}}"
    ENV_TRACE_DB_ENABLED: "{{ .Values.env.traceDbEnabled }}"
    ENV_REDIS_PASS: "{{ .Values.redis.password }}"
    JAEGER_SERVICE_NAME: "{{ .Values.env.jaeger.serviceName }}"
    JAEGER_SAMPLER_TYPE: "{{ .Values.env.jaeger.sampler }}"
    JAEGER_SAMPLER_PARAM: "{{ .Values.env.jaeger.samplerParam }}"
    JAEGER_ENDPOINT: "{{ .Values.env.jaeger.endpoint }}"
    JAEGER_REPORTER_LOG_SPANS: "{{ .Values.env.jaeger.reporterLogSpans }}"
